app_id: "be7d57c8-3a09-49b9-9cc4-777cfc9ba0eb"
app_secret: "39d346E1Ri6A.JV~4Q-w1.NyBbPodxQ9~Q"
scopes: "openid profile offline_access user.read calendars.read"

#app_id: "ac94ef81-cdc5-4c1a-a865-8f9d4dd769f5"
#app_secret: "el2.yKPFT24q-fGk-2O~k5075gWrbvK~us"
#scopes: "User.ReadBasic.All"

redirect: "https://bonas-app-service.azurewebsites.net/callback"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"



